### ISSUE TITLE
Check with Nial

### ISSUE THREAD

**Issue by yannikbehr** [yannikbehr/spectroscopy#1]
- [x] Can elements define new tags or do they have to be registered globally first?
- [ ] Datetimes are currently stored and returned as ISO 8601 strings as pytables is not capable of storing numpy.datetime64 or datetime.datetime objects. What are the potential problems with this? What would be a better solution?
- [ ] Why did we expect the following behaviour?: 
```
d = Dataset(tempfile.mktemp(), 'w')
with self.assertRaises(AttributeError):
    d.raw_data = []
d.raw_data[0] = 5
self.assertNotEqual(d.raw_data[0], 5)
```

**Comment by nonbiostudent** [comment]
- I think that tags have to be registered globally first. This was to make the maintenance of the tag list in the HDF5 file easier.
- ISO 8601 should be ok I think. Perhaps they should be returned as numpy.datetime64 objects though just to make life easier for the user. Not sure.....
- Dataset.raw_data should only be modifiable using the accessor methods (was it called append()?). Otherwise the raw data might get modified, leading to derived data being out of sync. The test protects against me changing spectra data that might be linked to from a flux element for example.

**Comment by yannikbehr** [comment]
I totally agree with registering tags globally. That's how I've implemented it. It's just not how we implemented it back in January, that's why I was asking.

I'll change the return value of datetimes to be numpy.datetime64.

Dataset.raw_data used to be a list of RawData objects contained within the dataset. We probably wanted to make sure that no one can accidentally tinker with that list as it's only for internal book keeping. I think I'll just add a '_' to make that clear.

**Comment by yannikbehr** [comment]
Some more thoughts on the return types: so far I've been returning the pytables objects (packaged with RetVal to prevent write access). I could also return numpy arrays but that would mean losing the efficiency of pytables when dealing with large arrays, as they would always be read into memory before slicing.
